version: '3.8'

services:
  # --- 1. ÖLÜMSÜZ VERİTABANI (POSTGRESQL) ---
  postgres:
    image: postgres:15
    container_name: albilet_db
    environment:
      POSTGRES_USER: kuto_user
      POSTGRES_PASSWORD: kuto_password
      POSTGRES_DB: albilet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # --- 2. HIZLI CACHE VE KOLTUK KİLİTLEME (REDİS) ---
  redis:
    image: redis:alpine
    container_name: albilet_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # --- 3. MESAJ KUYRUĞU (KAFKA & ZOOKEEPER) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: albilet_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: albilet_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  pgdata: